matrix:
  include:
    - language: python
      python:
        - "3.6"
      services: mysql
      env:
        DJANGO_VERSION=2.2.6
      install:
        - pip install -r requirements.txt
      #before_script:
      #  - mysql -e 'create database mysite_db;'
      #  - python manage.py syncdb --noinput
      script:
        - python manage.py test

    - language: node_js
      node_js:
        - 12.18.4
      before_install:
        - cd FE
      install:
        - npm install
      script:
        - npm run test
notifications:
  email: false